language: node_js
node_js:
  - "10"
services: mongodb
cache:
  directories:
    - "node_modules"
    - "$HOME/.npm"
  npm: true
matrix:
  fast_finish: true
  include:
    - env: APP=client
      before_install:
        - cd ${TRAVIS_BUILD_DIR}/client
      before_script:
        - sleep 10
      install:
        - npm install 
      script:
        - npm run test
    - env: APP=server
      before_install:
        - cd ${TRAVIS_BUILD_DIR}/server
      before_script:
        - sleep 10
      install:
        - npm install 
      script:
        - npm run test
on:
  branch: master
